[package]
name = "model-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"
bip39 = "2.0"
hex = "0.4"
hkdf.workspace = true
libc = "0.2"
rand = "0.8"
secp256k1 = { workspace = true, features = ["global-context", "rand-std"] }
sha2 = "0.10"
thiserror = "1.0"
zeroize.workspace = true

kaspa-addresses = { workspace = true }
kaspa-consensus-core = { workspace = true }

[dev-dependencies]
tempfile = "3.9"
