#!/usr/bin/env bash
# HiveOS configuration script for genome-miner
# This script is sourced by /hive/bin/custom, not executed directly

# Debug: log what HiveOS is passing
echo "[h-config] DEBUG: CUSTOM_TEMPLATE=${CUSTOM_TEMPLATE:-<empty>}" >&2
echo "[h-config] DEBUG: CUSTOM_URL=${CUSTOM_URL:-<empty>}" >&2
echo "[h-config] DEBUG: CUSTOM_USER_CONFIG=${CUSTOM_USER_CONFIG:-<empty>}" >&2

MINER_NAME="${MINER_NAME:-genome-miner}"

# Set default config filename if not provided by HiveOS
CUSTOM_CONFIG_FILENAME="${CUSTOM_CONFIG_FILENAME:-/hive/miners/custom/${MINER_NAME}/${MINER_NAME}.conf}"

# HiveOS provides these variables:
# CUSTOM_URL        Pool/node URL (host:port or stratum://host:port)
# CUSTOM_TEMPLATE   Mining address (wallet)
# CUSTOM_PASS       Password field from flight sheet (unused)
# CUSTOM_USER_CONFIG Extra CLI flags (e.g. "--gpu 0,1 --devnet")

# Extract mining address from CUSTOM_TEMPLATE or CUSTOM_USER_CONFIG
MINING_ADDRESS="${CUSTOM_TEMPLATE}"

# If CUSTOM_TEMPLATE is empty or a placeholder, try to extract from CUSTOM_USER_CONFIG
if [[ -z "${MINING_ADDRESS}" ]] || [[ "${MINING_ADDRESS}" =~ %WAL% ]]; then
    echo "[h-config] CUSTOM_TEMPLATE is placeholder/empty, extracting from CUSTOM_USER_CONFIG..." >&2
    # Try to extract xenom:qzq... address from user config
    MINING_ADDRESS=$(echo "${CUSTOM_USER_CONFIG:-}" | grep -oP 'xenom:[a-z0-9]{63}' | head -1)
fi

if [[ -z "${MINING_ADDRESS}" ]]; then
    echo "ERROR: Mining address not found in CUSTOM_TEMPLATE or CUSTOM_USER_CONFIG"
    echo "Please set wallet address in flight-sheet Template field or User Config"
    return 1 2>/dev/null || exit 1
fi

echo "[h-config] Mining address: ${MINING_ADDRESS}" >&2

# Extract worker name if present in format wallet.worker
WORKER_SUFFIX=""
if echo "${CUSTOM_USER_CONFIG:-}" | grep -qP 'xenom:[a-z0-9]{63}\.[a-zA-Z0-9_-]+'; then
    WORKER_SUFFIX=$(echo "${CUSTOM_USER_CONFIG:-}" | grep -oP 'xenom:[a-z0-9]{63}\.\K[a-zA-Z0-9_-]+' | head -1)
    echo "[h-config] Worker suffix: ${WORKER_SUFFIX}" >&2
fi

RPCSERVER="${CUSTOM_URL:-localhost:36669}"
# Strip protocol prefix if present
RPCSERVER="${RPCSERVER#*://}"
RPCSERVER="${RPCSERVER%%/*}"
RPCSERVER="${RPCSERVER:-localhost:36669}"

API_PORT=4000
LOG_DIR="/var/log/miner/${MINER_NAME}"

# Normalize newlines/tabs in user config to spaces (HiveOS JSON may embed \n)
USER_CONFIG="$(printf '%s' "${CUSTOM_USER_CONFIG:-}" | tr '\n\t' '  ' | tr -s ' ')"
# Remove --user and duplicate --stratum (already added via CUSTOM_URL)
USER_CONFIG="$(echo "${USER_CONFIG}" | sed 's/--user[[:space:]]\+[^[:space:]]\+//g' | sed 's/--stratum[[:space:]]\+[^[:space:]]\+//g' | tr -s ' ')"

# ── GPU selection ─────────────────────────────────────────────────────────
GPU_ARG="--gpu all"
if echo "${USER_CONFIG}" | grep -qE '\-\-gpu[[:space:]]'; then
    GPU_ARG=""
fi

# ── Network flag ──────────────────────────────────────────────────────────
NETWORK_ARG="--mainnet"
if echo "${USER_CONFIG}" | grep -qE '\-\-(testnet|devnet)'; then
    NETWORK_ARG=""
fi

# ── Assemble argument string ──────────────────────────────────────────────
# Add worker suffix to mining address if present
FINAL_ADDRESS="${MINING_ADDRESS}"
if [[ -n "${WORKER_SUFFIX}" ]]; then
    FINAL_ADDRESS="${MINING_ADDRESS}.${WORKER_SUFFIX}"
fi

MINER_ARGS="--mining-address ${FINAL_ADDRESS}"

# Add --stratum if CUSTOM_URL is set (pool mining mode)
if [[ -n "${CUSTOM_URL:-}" ]]; then
    MINER_ARGS="${MINER_ARGS} --stratum ${RPCSERVER}"
else
    # Solo mining mode - use --rpcserver
    MINER_ARGS="${MINER_ARGS} --rpcserver ${RPCSERVER}"
fi

[[ -n "${NETWORK_ARG}" ]] && MINER_ARGS="${MINER_ARGS} ${NETWORK_ARG}"
[[ -n "${GPU_ARG}" ]]     && MINER_ARGS="${MINER_ARGS} ${GPU_ARG}"
MINER_ARGS="${MINER_ARGS} --no-tui --api-port ${API_PORT}"
[[ -n "${USER_CONFIG}" ]] && MINER_ARGS="${MINER_ARGS} ${USER_CONFIG}"
MINER_ARGS="$(echo "${MINER_ARGS}" | tr -s ' ' | sed 's/^ //;s/ $//')"

mkdir -p "$(dirname "$CUSTOM_CONFIG_FILENAME")" "$LOG_DIR"

cat > "$CUSTOM_CONFIG_FILENAME" <<EOF
# genome-miner HiveOS config — generated by h-config.sh
MINER_ARGS="${MINER_ARGS}"
API_PORT="${API_PORT}"
LOG_DIR="${LOG_DIR}"
EOF

echo "genome-miner config generated:"
cat "$CUSTOM_CONFIG_FILENAME"
