#!/usr/bin/env bash
# ── h-config.sh ───────────────────────────────────────────────────────────────
# Called by HiveOS to generate the miner configuration file from flight-sheet
# parameters before h-run.sh starts the miner.
#
# HiveOS injects these environment variables from the flight-sheet:
#
#   CUSTOM_TEMPLATE     — Mining reward address (wallet)
#   CUSTOM_URL          — Xenom node gRPC endpoint  e.g. "192.168.1.10:36669"
#   CUSTOM_PASS         — (unused by genome-miner)
#   CUSTOM_USER_CONFIG  — Extra CLI flags, e.g. "--gpu all --mainnet"
#   CUSTOM_CONFIG_FILENAME — Full path where config file must be written
#   WORKER_NAME         — HiveOS rig worker name (informational)
#
# Output: a shell-sourceable config file at $CUSTOM_CONFIG_FILENAME containing
# the complete argument string that h-run.sh will pass to genome-miner.
# ─────────────────────────────────────────────────────────────────────────────
# HiveOS sources this file — do NOT use set -euo pipefail at top level.
# All wallet/rig variables (CUSTOM_TEMPLATE, CUSTOM_URL, etc.) are already
# in scope when HiveOS sources this script.

MINER_NAME="genome-miner"

miner_config_gen() {
    local MINER_DIR="/hive/miners/custom/${MINER_NAME}"
    local CONFIG_FILE="${CUSTOM_CONFIG_FILENAME:-${MINER_DIR}/${MINER_NAME}.conf}"

    # ── Validate required fields ──────────────────────────────────────────────
    if [[ -z "${CUSTOM_TEMPLATE:-}" ]]; then
        echo "[h-config] ERROR: Mining address (Wallet) not set in flight-sheet."
        return 1
    fi

    local MINING_ADDRESS="${CUSTOM_TEMPLATE}"

    # ── Parse pool/node endpoint ──────────────────────────────────────────────
    local RPCSERVER="${CUSTOM_URL:-localhost:36669}"
    RPCSERVER="${RPCSERVER#*://}"
    RPCSERVER="${RPCSERVER%%/*}"
    RPCSERVER="${RPCSERVER:-localhost:36669}"

    # ── GPU selection ─────────────────────────────────────────────────────────
    local GPU_ARG="--gpu all"
    if echo "${CUSTOM_USER_CONFIG:-}" | grep -qE '\-\-gpu[[:space:]]'; then
        GPU_ARG=""
    fi

    # ── Network flag ──────────────────────────────────────────────────────────
    local NETWORK_ARG="--mainnet"
    if echo "${CUSTOM_USER_CONFIG:-}" | grep -qE '\-\-(testnet|devnet)'; then
        NETWORK_ARG=""
    fi

    # ── Assemble argument string ──────────────────────────────────────────────
    local MINER_ARGS="--mining-address ${MINING_ADDRESS} --rpcserver ${RPCSERVER}"
    [[ -n "${NETWORK_ARG}" ]] && MINER_ARGS="${MINER_ARGS} ${NETWORK_ARG}"
    [[ -n "${GPU_ARG}" ]]     && MINER_ARGS="${MINER_ARGS} ${GPU_ARG}"
    MINER_ARGS="${MINER_ARGS} --no-tui --api-port 4000"
    [[ -n "${CUSTOM_USER_CONFIG:-}" ]] && MINER_ARGS="${MINER_ARGS} ${CUSTOM_USER_CONFIG}"
    MINER_ARGS="$(echo "${MINER_ARGS}" | tr -s ' ' | sed 's/^ //;s/ $//')"

    # ── Write config file ─────────────────────────────────────────────────────
    mkdir -p "$(dirname "${CONFIG_FILE}")"
    cat > "${CONFIG_FILE}" << CONF
# genome-miner HiveOS config — generated by h-config.sh
MINER_ARGS="${MINER_ARGS}"
CONF

    echo "[h-config] Config written to: ${CONFIG_FILE}"
    echo "[h-config] Args: ${MINER_ARGS}"
}

# HiveOS (both miner-run and /hive/bin/custom) sources this file and then calls
# miner_config_gen explicitly. Do NOT call it inline here.
