CUSTOM_NAME="genome-miner"
CUSTOM_VERSION="0.15.3"
CUSTOM_CONFIG_FILENAME="/hive/miners/custom/genome-miner/genome-miner.conf"
CUSTOM_LOG_BASENAME="/var/log/miner/genome-miner/genome-miner"

miner_ver() { echo "${CUSTOM_VERSION}"; }
