#!/usr/bin/env bash
# ── h-run.sh ──────────────────────────────────────────────────────────────────
# Called by HiveOS to start the genome-miner GPU miner.
#
# Flow:
#   1. Source the config file generated by h-config.sh
#   2. Ensure the GRCh38 genome dataset is present (auto-download if absent)
#   3. Prepare the log directory
#   4. exec genome-miner gpu <args>
#
# HiveOS restarts this script automatically if the miner process exits.
# The --no-tui flag is mandatory (HiveOS has no interactive terminal).
# The --api-port 4000 flag enables the stats API read by h-stats.sh.
# ─────────────────────────────────────────────────────────────────────────────

MINER_NAME="genome-miner"
MINER_DIR="/hive/miners/custom/${MINER_NAME}"
MINER_BIN="${MINER_DIR}/${MINER_NAME}"
CONFIG_FILE="${CUSTOM_CONFIG_FILENAME:-${MINER_DIR}/${MINER_NAME}.conf}"
LOG_DIR="/var/log/miner/${MINER_NAME}"
LOG_FILE="${LOG_DIR}/${MINER_NAME}.log"

# Canonical genome download URL (GitHub Releases)
GENOME_URL="https://github.com/hainakus/Xenomorph/releases/download/genome-grch38-v0/grch38.xenom"
# Primary local storage path (also the genome-miner auto-detect default)
GENOME_DEFAULT_DIR="${HOME}/.rusty-xenom"
GENOME_DEFAULT_PATH="${GENOME_DEFAULT_DIR}/grch38.xenom"
# Minimum expected file size in bytes (~780 MB)
GENOME_MIN_BYTES=780000000

# ── Sanity checks ─────────────────────────────────────────────────────────────
if [[ ! -x "${MINER_BIN}" ]]; then
    echo "[h-run] ERROR: Binary not found or not executable: ${MINER_BIN}"
    exit 1
fi

if [[ ! -f "${CONFIG_FILE}" ]]; then
    echo "[h-run] ERROR: Config file not found: ${CONFIG_FILE}"
    echo "        Run h-config.sh first (HiveOS does this automatically)."
    exit 1
fi

# ── Load config ───────────────────────────────────────────────────────────────
# shellcheck source=/dev/null
source "${CONFIG_FILE}"

if [[ -z "${MINER_ARGS:-}" ]]; then
    echo "[h-run] ERROR: MINER_ARGS is empty in ${CONFIG_FILE}"
    exit 1
fi

# ── Genome dataset: detect, verify, or download ───────────────────────────────
# Search order: explicit --genome-file in args > known local paths > download.

genome_file_size() {
    local f="$1"
    stat -c%s "${f}" 2>/dev/null || stat -f%z "${f}" 2>/dev/null || echo 0
}

genome_ok() {
    local f="$1"
    [[ -f "${f}" ]] && [[ $(genome_file_size "${f}") -ge ${GENOME_MIN_BYTES} ]]
}

download_genome() {
    local dest="$1"
    mkdir -p "$(dirname "${dest}")"
    echo "[h-run] Genome dataset not found — downloading (~780 MB)..."
    echo "[h-run] Source : ${GENOME_URL}"
    echo "[h-run] Dest   : ${dest}"
    echo "[h-run] Download will resume automatically if interrupted."

    if command -v wget &>/dev/null; then
        # -c = resume  --show-progress = live progress bar
        wget -c --show-progress -q "${GENOME_URL}" -O "${dest}"
    elif command -v curl &>/dev/null; then
        # -C - = resume  --progress-bar = live bar
        curl -L -C - --progress-bar "${GENOME_URL}" -o "${dest}"
    else
        echo "[h-run] ERROR: Neither wget nor curl found. Cannot download genome."
        echo "        Install one and retry, or copy grch38.xenom manually to:"
        echo "        ${dest}"
        exit 1
    fi

    if genome_ok "${dest}"; then
        echo "[h-run] Genome download complete: ${dest}  ($(genome_file_size "${dest}") bytes)"
    else
        echo "[h-run] ERROR: Downloaded file appears incomplete or corrupt."
        echo "        Expected >= ${GENOME_MIN_BYTES} bytes, got $(genome_file_size "${dest}")."
        echo "        The file will be re-attempted on next start (wget/curl resume)."
        # Remove partial file only if empty; keep partial for resume
        [[ $(genome_file_size "${dest}") -eq 0 ]] && rm -f "${dest}"
        exit 1
    fi
}

# If --genome-file is already in MINER_ARGS, honour it but still verify.
GENOME_PATH=""
if echo "${MINER_ARGS}" | grep -q '\-\-genome-file'; then
    GENOME_PATH=$(echo "${MINER_ARGS}" | grep -oP '(?<=--genome-file )\S+')
    if genome_ok "${GENOME_PATH}"; then
        echo "[h-run] Genome dataset (from args): ${GENOME_PATH}"
    else
        echo "[h-run] WARN: --genome-file path invalid or incomplete: ${GENOME_PATH}"
        echo "        Falling back to default location."
        GENOME_PATH=""
        # Strip the invalid --genome-file argument so we can inject the correct one
        MINER_ARGS=$(echo "${MINER_ARGS}" | sed 's/--genome-file[[:space:]]\+\S\+//g' | tr -s ' ')
    fi
fi

# Search well-known local paths if not already resolved
if [[ -z "${GENOME_PATH}" ]]; then
    GENOME_CANDIDATES=(
        "${MINER_DIR}/grch38.xenom"
        "${GENOME_DEFAULT_PATH}"
        "/data/genome/grch38.xenom"
    )
    for GPATH in "${GENOME_CANDIDATES[@]}"; do
        if genome_ok "${GPATH}"; then
            GENOME_PATH="${GPATH}"
            echo "[h-run] Genome dataset found: ${GENOME_PATH}"
            break
        fi
    done
fi

# Still nothing — download it now
if [[ -z "${GENOME_PATH}" ]]; then
    download_genome "${GENOME_DEFAULT_PATH}"
    GENOME_PATH="${GENOME_DEFAULT_PATH}"
fi

# Inject --genome-file into args if not already present
if ! echo "${MINER_ARGS}" | grep -q '\-\-genome-file'; then
    MINER_ARGS="${MINER_ARGS} --genome-file ${GENOME_PATH}"
fi

# ── Prepare log directory ─────────────────────────────────────────────────────
mkdir -p "${LOG_DIR}"

# Rotate log: keep last 50 MB
if [[ -f "${LOG_FILE}" ]] && [[ $(stat -c%s "${LOG_FILE}" 2>/dev/null || echo 0) -gt 52428800 ]]; then
    mv "${LOG_FILE}" "${LOG_FILE}.1"
fi

echo "[h-run] Starting: ${MINER_BIN} gpu ${MINER_ARGS}"
echo "[h-run] Log:      ${LOG_FILE}"

# ── Launch miner ──────────────────────────────────────────────────────────────
# exec replaces this shell — HiveOS monitors the PID directly.
# stdout/stderr go to the log file so hive-client can tail them.
exec "${MINER_BIN}" gpu ${MINER_ARGS} 2>&1 | tee -a "${LOG_FILE}"
